import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { WorkOrderEntity, WorkOrderStatus, WorkOrderPriority } from '../../database/entities/work-order.entity';
import { OpinionEventEntity } from '../../database/entities/opinion-event.entity';

export interface IncidentReport {
  workOrderId: number;
  eventId: number;
  title: string;
  description: string;
  riskLevel: string;
  autoGeneratedActions: string[];
  status: WorkOrderStatus;
}

@Injectable()
export class IncidentWorkflowService {
  private readonly logger = new Logger(IncidentWorkflowService.name);

  constructor(
    @InjectRepository(WorkOrderEntity)
    private readonly workOrderRepo: Repository<WorkOrderEntity>,
    @InjectRepository(OpinionEventEntity)
    private readonly eventRepo: Repository<OpinionEventEntity>,
  ) {}

  async createIncidentFromEvent(eventId: number, createdBy: number): Promise<IncidentReport> {
    const event = await this.eventRepo.findOne({ where: { id: eventId } });
    if (!event) {
      throw new Error(`Event ${eventId} not found`);
    }

    const riskLevel = this.determineRiskLevel(event);
    const priority = this.riskToPriority(riskLevel);
    const actions = this.generateActions(riskLevel, event);

    const workOrder = this.workOrderRepo.create({
      userId: createdBy,
      type: 'incident' as any,
      title: `[自动处置] ${event.title.substring(0, 100)}`,
      description: this.buildDescription(event, actions),
      priority,
      status: WorkOrderStatus.PENDING,
      eventId: event.id,
    } as any);

    const saved = await this.workOrderRepo.save(workOrder) as any;
    this.logger.log(`Created incident work order ${saved.id} from event ${eventId}`);

    return {
      workOrderId: saved.id,
      eventId: event.id,
      title: saved.title,
      description: saved.description,
      riskLevel,
      autoGeneratedActions: actions,
      status: saved.status,
    };
  }

  async autoAssign(workOrderId: number, userId: number): Promise<void> {
    await this.workOrderRepo.update(workOrderId, {
      assignedTo: userId,
      status: WorkOrderStatus.IN_PROGRESS,
    });
    this.logger.log(`Assigned work order ${workOrderId} to user ${userId}`);
  }

  async completeWithFeedback(workOrderId: number, feedback: string): Promise<void> {
    await this.workOrderRepo.update(workOrderId, {
      status: WorkOrderStatus.RESOLVED,
      feedback,
    });
    this.logger.log(`Work order ${workOrderId} completed`);
  }

  private determineRiskLevel(event: OpinionEventEntity): string {
    const isNegative = event.sentiment === 'negative';
    const highReads = event.readCount > 10000;
    const highComments = event.commentCount > 500;

    if (isNegative && highReads && highComments) return 'critical';
    if (isNegative && (highReads || highComments)) return 'high';
    if (isNegative) return 'medium';
    return 'low';
  }

  private riskToPriority(risk: string): WorkOrderPriority {
    const map: Record<string, WorkOrderPriority> = {
      critical: WorkOrderPriority.HIGH,
      high: WorkOrderPriority.HIGH,
      medium: WorkOrderPriority.MEDIUM,
      low: WorkOrderPriority.LOW,
    };
    return map[risk] || WorkOrderPriority.MEDIUM;
  }

  private generateActions(riskLevel: string, event: OpinionEventEntity): string[] {
    const actions: string[] = [];
    actions.push(`【核实】确认事件 ${event.id} 的真实性和来源`);
    actions.push(`【分析】评估事件 ${event.id} 的传播范围和影响程度`);

    if (riskLevel === 'critical') {
      actions.push('【上报】立即上报至上级主管部门');
      actions.push('【响应】准备官方声明，启动危机公关预案');
      actions.push('【处置】联系相关平台处理高热度负面内容');
    } else if (riskLevel === 'high') {
      actions.push('【上报】上报至部门负责人审批');
      actions.push('【响应】加强监测频次，每30分钟输出分析报告');
    } else {
      actions.push('【归档】纳入常规监测，每日输出分析报告');
    }

    return actions;
  }

  private buildDescription(event: OpinionEventEntity, actions: string[]): string {
    return [
      `舆情事件自动处置工单`,
      ``,
      `事件 ID: ${event.id}`,
      `标题: ${event.title}`,
      `平台: ${event.platform}`,
      `作者: ${event.author}`,
      `发布时间: ${event.publishTime.toISOString()}`,
      `情感倾向: ${event.sentiment}`,
      `阅读量: ${event.readCount}`,
      `评论数: ${event.commentCount}`,
      ``,
      `=== 自动处置建议 ===`,
      ...actions.map((a, i) => `${i + 1}. ${a}`),
    ].join('\n');
  }
}