packages:
  - 'backend'
  - 'frontend-admin'
  - 'frontend-user'
  - 'frontend-shared'
allowBuilds:
  '@alicloud/openapi-core': true
  '@nestjs/core': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  vue-demi: true
